### ISSUE TITLE
Exceptions in GreedySwitch

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#155]
The following AIOOBE occurs for a graph with a single node: 
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.CrossingMatrixFiller.<init>(CrossingMatrixFiller.java:38)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.getNewSwitchDecider(GreedySwitchHeuristic.java:87)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.setUp(GreedySwitchHeuristic.java:82)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.setFirstLayerOrder(GreedySwitchHeuristic.java:74)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsNoCounter(LayerSweepCrossingMinimizer.java:154)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.lambda$1(LayerSweepCrossingMinimizer.java:122)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:131)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:110)
```

**Comment by uruuru** [comment]
The issue seems to occur mainly in conjunction with hierarchical layout. If greedy switch is deactivated somewhere in the hierarchy (e.g. due to its `activationThreshold`), while being activated at the root, it tries to run on an empty graph which results in the out of bound exceptions.
