### ISSUE TITLE
IllegalStateException in BasicProgressMonitor

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#172]
Every once in a while, using automatic layout triggers the following exception:

```
Exception in thread "pool-2-thread-9" java.lang.IllegalStateException: The task has not begun yet.
    at org.eclipse.elk.core.util.BasicProgressMonitor.done(BasicProgressMonitor.java:139)
    at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:410)
    at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by le-cds** [comment]
Should be fixed. It's not clear how to reproduce this issue. If the issue persists even with this change, we may have to stop throwing the `IllegalStateException` in `BasicProgressMonitor` in the first place.

**Comment by heeckhau** [comment]
In the layout methods (org.eclipse.elk.core.service.DiagramLayoutEngine.layout) there is:
```
if (monitor.isCanceled()) {
         return Status.CANCEL_STATUS;
}
```
before the begin method on the monitor is called.

This results in the `IllegalStateException` when `monitor.done()` is called in org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute

At first sight, it looks like calling `done()` is not necessary in `execute()` because it is already called where `begin()` is called.

**Comment by le-cds** [comment]
Hendrik, thanks for looking into this.

> At first sight, it looks like calling `done()` is not necessary in `execute()` because it is already called where `begin()` is called.

Sounds reasonable. However, since I don't currently have an afternoon to spend on understanding the interactions involved here, I simply guarded the `done()` call to only execute only if the progress monitor is still running.
