### ISSUE TITLE
ArrayIndexOutOfBoundsException in Layered layout algorithm

### ISSUE THREAD

**Issue by memin20** [eclipse/elk#248]
With the attached file it's possible to reproduce the exception below.
In most cases it works, but in that special case it doesn't work. Elk version 0.1.0

[Reproduction.zip](https://github.com/eclipse/elk/files/1306362/Reproduction.zip)

!ENTRY org.eclipse.ui 4 0 2017-09-15 14:32:38.577
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.CrossingMatrixFiller.<init>(CrossingMatrixFiller.java:38)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.getNewSwitchDecider(GreedySwitchHeuristic.java:87)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.setUp(GreedySwitchHeuristic.java:82)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.setFirstLayerOrder(GreedySwitchHeuristic.java:74)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsNoCounter(LayerSweepCrossingMinimizer.java:154)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.lambda$1(LayerSweepCrossingMinimizer.java:122)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:131)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:110)
	at org.eclipse.elk.alg.layered.KlayLayered.hierarchicalLayout(KlayLayered.java:233)
	at org.eclipse.elk.alg.layered.KlayLayered.doCompoundLayout(KlayLayered.java:179)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:58)

**Comment by uruuru** [comment]
I'm closing this for now. Let me know if your issue persists.
