### ISSUE TITLE
AIOB in LayoutViewPart

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#25]
In some scenarios there seem to be an array index out of bounds in the layout view.

```
java.lang.ArrayIndexOutOfBoundsException: 12
	at org.eclipse.ui.views.properties.PropertySheetViewer.updateChildrenOf(PropertySheetViewer.java:1319)
	at org.eclipse.ui.views.properties.PropertySheetViewer.updateChildrenOf(PropertySheetViewer.java:1322)
	at org.eclipse.ui.views.properties.PropertySheetViewer.access$2(PropertySheetViewer.java:1221)
	at org.eclipse.ui.views.properties.PropertySheetViewer$3.childEntriesChanged(PropertySheetViewer.java:330)
	at org.eclipse.ui.views.properties.PropertySheetEntry.fireChildEntriesChanged(PropertySheetEntry.java:304)
	at org.eclipse.ui.views.properties.PropertySheetEntry.refreshChildEntries(PropertySheetEntry.java:555)
	at org.eclipse.ui.views.properties.PropertySheetEntry.setValues(PropertySheetEntry.java:736)
	at org.eclipse.ui.views.properties.PropertySheetViewer.setInput(PropertySheetViewer.java:986)
	at org.eclipse.ui.views.properties.PropertySheetViewer.setRootEntry(PropertySheetViewer.java:1033)
	at org.eclipse.ui.views.properties.PropertySheetPage.setPropertySourceProvider(PropertySheetPage.java:564)
	at org.eclipse.elk.core.ui.views.LayoutViewPart.lambda$0(LayoutViewPart.java:118)
	at org.eclipse.elk.core.ui.views.LayoutViewPart$$Lambda$1/342735014.selectionChanged(Unknown Source)
[...]
```

**Comment by le-cds** [comment]
This was apparently caused by the way we handled legacy IDs for layout options. So far, a given `LayoutOptionData` instance appeared arbitrarily many times in the `LayoutMetaDataService`'s layout option map: once for its primary ID, and once for each additional legacy ID. This caused the layout view to show layout options multiple times. However, the property sheet the view is based on seems to filter out entries that are the same object. Thus, we ended up with an array of options that was not completely filled, and bad things happened (tm).

I fixed it by having each layout option appear only once in the layout option map. The mapping of legacy IDs to `LayoutOptionData` instances happens in a separate map.
