### ISSUE TITLE
ConcurrentModificationException in Debug View

### ISSUE THREAD

**Issue by Kabumm27** [eclipse/elk#264]
```
Caused by: java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692)
	at org.eclipse.emf.ecore.util.EcoreUtil$Copier.copyReference(EcoreUtil.java:772)
	at org.eclipse.emf.ecore.util.EcoreUtil$Copier.copyReferences(EcoreUtil.java:688)
	at org.eclipse.emf.ecore.util.EcoreUtil.copy(EcoreUtil.java:358)
	at org.eclipse.elk.core.debug.views.graph.LayoutGraphView$1.run(LayoutGraphView.java:57)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 40 more
```

The issue occurs non-deterministically.

**Comment by le-cds** [comment]
The debug view has seen a major overhaul and I haven't seen the issue since then.
