### ISSUE TITLE
Odd exceptions during layout

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#266]
From time to time laying out the following graph raises the exceptions below. Happens with the `force` layouter, not with `layered`. It's possible that it's not related to ELK but to KIELER. 

```
node n1 {
	port p0
}

node n2 {
	port p1
	node n3 {
		port p1
		port p2
	}
	node n4	{
		port p1
		port p2
	}
	node n5	{
		port p1
		port p2
	}
	node n6	{
		port p1
		port p2
		port p3
	}
	node n7	{
		port p1
		port p2
	}
	node n8	{
		port p1
		port p2
	}
	node n9	{
		port p1
		port p2
	}
	node n10 {
		port p1
		port p2
	}
	
	edge e2: n3.p2 -> n4.p1
	edge e3: n4.p2 -> n5.p1
	edge e4: n5.p2 -> n6.p1
	edge e5: n6.p2 -> n7.p1
	edge e6: n7.p2 -> n8.p1
	edge e7: n8.p2 -> n9.p1
	edge e8: n9.p2 -> n10.p1
	edge e9: n10.p2 -> n3.p1
	edge e10: p1 -> n6.p3
}

edge e0: n1.p0 -> n2.p1
```

```
java.lang.IllegalArgumentException: Passed edge is not 'simple'.
    at org.eclipse.elk.graph.util.ElkGraphUtil.getSourceNode(ElkGraphUtil.java:629)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.adjustEdgeEndpoints(KlighdDiagramLayoutConnector.java:1067)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.edgeToViewModel(KlighdDiagramLayoutConnector.java:983)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.access$2(KlighdDiagramLayoutConnector.java:973)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector$1.caseElkEdge(KlighdDiagramLayoutConnector.java:667)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector$1.caseElkEdge(KlighdDiagramLayoutConnector.java:1)
    at org.eclipse.elk.graph.util.ElkGraphSwitch.doSwitch(ElkGraphSwitch.java:156)
    at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
    at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.applyLayout(KlighdDiagramLayoutConnector.java:707)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.applyLayout(KlighdDiagramLayoutConnector.java:621)
    at org.eclipse.elk.core.service.DiagramLayoutEngine$1.postUIexec(DiagramLayoutEngine.java:410)
    at org.eclipse.elk.core.service.util.MonitoredOperation.runUnmonitored(MonitoredOperation.java:255)
    at org.eclipse.elk.core.service.util.MonitoredOperation.runUnmonitored(MonitoredOperation.java:157)
    at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:428)
    at org.eclipse.elk.core.service.DiagramLayoutEngine.invokeLayout(DiagramLayoutEngine.java:282)
    at org.eclipse.elk.core.service.DiagramLayoutEngine.invokeLayout(DiagramLayoutEngine.java:245)
    [...]
```

```
java.lang.IllegalArgumentException: Edge must have exactly one source and one target
    at de.cau.cs.kieler.klighd.kgraph.util.KGraphUtil.toKGraphCoordinateSystem(KGraphUtil.java:468)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.edgeToViewModel(KlighdDiagramLayoutConnector.java:993)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.access$2(KlighdDiagramLayoutConnector.java:973)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector$1.caseElkEdge(KlighdDiagramLayoutConnector.java:667)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector$1.caseElkEdge(KlighdDiagramLayoutConnector.java:1)
    at org.eclipse.elk.graph.util.ElkGraphSwitch.doSwitch(ElkGraphSwitch.java:156)
    at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
    at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.applyLayout(KlighdDiagramLayoutConnector.java:707)
    at de.cau.cs.kieler.klighd.internal.macrolayout.KlighdDiagramLayoutConnector.applyLayout(KlighdDiagramLayoutConnector.java:621)
    at org.eclipse.elk.core.service.DiagramLayoutEngine$1.postUIexec(DiagramLayoutEngine.java:410)
    at org.eclipse.elk.core.service.util.MonitoredOperation.runUnmonitored(MonitoredOperation.java:255)
    at org.eclipse.elk.core.service.util.MonitoredOperation.runUnmonitored(MonitoredOperation.java:157)
    at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:428)
    at org.eclipse.elk.core.service.DiagramLayoutEngine.invokeLayout(DiagramLayoutEngine.java:282)
    at org.eclipse.elk.core.service.DiagramLayoutEngine.invokeLayout(DiagramLayoutEngine.java:245)
    [...]
```

**Comment by le-cds** [comment]
It is not clear yet whether this is really an issue in ELK or one in KLighD.

**Comment by le-cds** [comment]
I haven't heard of this for quite some time and it looks suspiciously like a problem with KLighD's incremental update. So I'll close this as invalid for the time being.
