### ISSUE TITLE
Another NPE in LGraphUtil#createExternalPortDummy

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/elk#272]
This appears to be related to #160. There are two other calls to LGraphUtil#createExternalPortDummy from CompoundGraphPreprocessor with a null portPosition. A NPE is thrown whenver that portion of the code is executed with fixed position ports. The example below triggers one of the code paths:

```
graph G1
hierarchyHandling: INCLUDE_CHILDREN
algorithm: org.eclipse.elk.layered
node N1 {
	node N2 {
		layout [
			size: 300,300
		]
	}
	
	node N4 {
		layout [
			size: 300, 300
		]
		portConstraints: FIXED_POS
		node N5 {
			layout [
				size: 200, 200
			]
			
		}
		
		port P1 {
			layout [
				position: 0, 50
				size: 20, 20
			]	
		} 
		
		edge E2: N4 -> N4.N5
	}
	
	edge E1: N2 -> N4
}
```

That produces:
```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.graph.LGraphUtil.createExternalPortDummy(LGraphUtil.java:867)
	at org.eclipse.elk.alg.layered.compound.CompoundGraphPreprocessor.transformHierarchyEdges(CompoundGraphPreprocessor.java:181)
	at org.eclipse.elk.alg.layered.compound.CompoundGraphPreprocessor.transformHierarchyEdges(CompoundGraphPreprocessor.java:161)
	at org.eclipse.elk.alg.layered.compound.CompoundGraphPreprocessor.process(CompoundGraphPreprocessor.java:109)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:180)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:58)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
	at org.eclipse.elk.core.debug.views.graph.LoadGraphAction.layout(LoadGraphAction.java:98)
	at org.eclipse.elk.core.debug.views.graph.LoadGraphAction.run(LoadGraphAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by philip-alldredge** [comment]
Were you able to reproduce this issue?

**Comment by le-cds** [comment]
Yes, I was. I'm scheduling this to be fixed for 0.4.0. Is it okay for you if we add your example to our official models repository under the EPL license?

**Comment by philip-alldredge** [comment]
Great. Yes, feel free to add the model to your repo under the EPL license.

**Comment by le-cds** [comment]
This issue is in fact a problem described in #60: ELK Layered can only handle hierarchical edges properly if all edges are connected to ports. In your case that would entail the following changes to your diagram:

* Have `E1` end in `N4.P1` instead of `N4`.
* Have `E2` start at `N4.P1` instead of `N4`.

While the other ticket does talk about adding support for edges connected directly to a node, in this case that would not make sense from a configuration perspective: port constraints are set to `FIXED_POS`. In a way, you are making a commitment to specify all ports and their positions. The algorithm wouldn't know where exactly edges not ending in a port should be placed.

For that reason, I'm closing this issue as invalid. If you have any questions or if I have missed anything, feel free to reopen the ticket.
