### ISSUE TITLE
Exceptions in spline selfloop code

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#283]
Quickly executing successive layout runs (for instance using KLighD's spacing slider), _sometimes_ yields the following two exceptions. I guess it's possible that the input graph's structure is broken, or at least doesn't match the processors' expectations. 

```
!ENTRY org.eclipse.elk.core.service 4 0 2018-01-31 14:56:06.767
!MESSAGE Failed to perform diagram layout.
!STACK 0
java.util.ConcurrentModificationException
    at java.base/java.util.ArrayList.sort(ArrayList.java:1587)
    at java.base/java.util.Collections.sort(Collections.java:175)
    at
org.eclipse.elk.alg.layered.intermediate.SplineSelfLoopPositioner$PortReadder.<init>(SplineSelfLoopPositioner.java:620)
    at
org.eclipse.elk.alg.layered.intermediate.SplineSelfLoopPositioner.portStackedPositioning(SplineSelfLoopPositioner.java:328)
    at
org.eclipse.elk.alg.layered.intermediate.SplineSelfLoopPositioner.process(SplineSelfLoopPositioner.java:145)
    at
org.eclipse.elk.alg.layered.intermediate.SplineSelfLoopPositioner.process(SplineSelfLoopPositioner.java:1)
    at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:550)
    at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:142)
    at
org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:61)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
    at
org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:682)
    at
org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:614)
    at
org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:382)
    at
org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
    at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.base/java.lang.Thread.run(Thread.java:844)
```
```
!ENTRY org.eclipse.elk.core.service 4 0 2018-01-31 14:56:45.284
!MESSAGE Failed to perform diagram layout.
!STACK 0
java.util.NoSuchElementException
    at java.base/java.util.ArrayList$Itr.next(ArrayList.java:894)
    at
org.eclipse.elk.alg.layered.intermediate.SplineSelfLoopRouter.process(SplineSelfLoopRouter.java:111)
    at
org.eclipse.elk.alg.layered.intermediate.SplineSelfLoopRouter.process(SplineSelfLoopRouter.java:1)
    at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:550)
    at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:142)
    at
org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:61)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:161)
    at
org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
    at
org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:682)
    at
org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:614)
    at
org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:382)
    at
org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
    at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by spoenemann** [comment]
We should implement #246 to get better feedback on invalid input.
