### ISSUE TITLE
NPE when combining cross-hierarchy edges, selfloops and splines

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#288]
Take the following example:
```
hierarchyHandling: INCLUDE_CHILDREN
//edgeRouting: SPLINES

node A1
node A2 {
	node B1
}
edge A2 -> A2
edge A1 -> A2.B1
```
If the `edgeRouting: SPLINES` is activated, a NPE is thrown.
```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKAligner.insideBlockShift(BKAligner.java:197)
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKNodePlacer.process(BKNodePlacer.java:230)
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKNodePlacer.process(BKNodePlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:237)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:182)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:58)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:682)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:614)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:382)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The NPE vanishes if orthogonal routing is used or one of the two edges is commented out.

**Comment by eNBeWe** [comment]
With a slightly more complex test case the NPE is thrown during crossing minimization instead of node placement:
```
elk.direction: RIGHT
hierarchyHandling: INCLUDE_CHILDREN
node N7 {
//	edgeRouting: SPLINES

	node N8
	node N2 {
		node N1
	}
	node N4
	
	edge N8 -> N2.N1
	edge N2 -> N2
	edge N2 -> N4
	edge N2.N1 -> N4
}
```
Stacktrace:
```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.p3order.AbstractBarycenterPortDistributor.updateNodePositions(AbstractBarycenterPortDistributor.java:323)
	at org.eclipse.elk.alg.layered.p3order.AbstractBarycenterPortDistributor.distributePortsWhileSweeping(AbstractBarycenterPortDistributor.java:83)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.sweepReducingCrossings(LayerSweepCrossingMinimizer.java:246)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.sweepInHierarchicalNode(LayerSweepCrossingMinimizer.java:285)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.sweepInHierarchicalNodes(LayerSweepCrossingMinimizer.java:264)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.sweepReducingCrossings(LayerSweepCrossingMinimizer.java:252)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsWithCounter(LayerSweepCrossingMinimizer.java:198)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.compareDifferentRandomizedLayouts(LayerSweepCrossingMinimizer.java:183)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.lambda$0(LayerSweepCrossingMinimizer.java:129)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:141)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:119)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:241)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:182)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:58)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:682)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:614)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:382)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by uruuru** [comment]
Both issues are due to an unfortunate interplay of hierarchical crossing minimization and spline self loop handling. 
The `SplineSelfLoopPreProcessor` potentially _hides_ (temporarily removes) ports to which only self loops connect. During crossing minimization the hierarchical layer sweep then fails to match hierarchical port dummies to the corresponding originating ports (which have been removed). This explains the second exception. In the case of the first exception the hierarchical layer sweep leaves behind an invalid graph structure, which is not noticed until node placement. 

I'll fix the issue by prohibiting the `SplineSelfLoopPreProcessor` from hiding ports when hierarchical layout is activated. As far as I could tell so far, the created self loops routes are broken in such cases afterwards. However, this is a different issue and will hopefully be fixed as soon as @le-cds merges a new spline self loop routing (which is in the pipeline).
