### ISSUE TITLE
Conservative big nodes and labels NPE 

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#332]
The conservative big nodes processor seems to fail to properly re-attach node labels and thus yields an NPE during layout application.

[Example to reproduce](https://github.com/eclipse/elk-models/blob/master/tests/layered/big_nodes/conservative/long_edge_incoming.elkt).

```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphLayoutTransferrer.applyNodeLayout(ElkGraphLayoutTransferrer.java:189)
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphLayoutTransferrer.applyLayout(ElkGraphLayoutTransferrer.java:98)
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.applyLayout(ElkGraphTransformer.java:41)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:66)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:231)
```

Problematic line (the second one):
```
ElkLabel elklabel = (ElkLabel) llabel.getProperty(InternalProperties.ORIGIN);
elklabel.setDimensions(llabel.getSize().x, llabel.getSize().y);
```

**Comment by le-cds** [comment]
@uruuru @spoenemann Seeing that we have horizontal compaction and since there are quite a few cases where big nodes processing fails, should we perhaps remove that from ELK Layered?

**Comment by le-cds** [comment]
Closing since we have since removed big nodes processing.
