### ISSUE TITLE
CCE in greedy switch with fixed ports

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#340]
Executing greedy switch on the following graph yields a `ClassCastException` when port constraints are set to `FIXED_POS`. 

A workaround is to deactivate greedy switch. 

```
java.lang.ClassCastException: org.eclipse.elk.alg.layered.graph.LEdge cannot be cast to org.eclipse.elk.alg.layered.graph.LNode
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.NorthSouthEdgeNeighbouringNodeCrossingsCounter.originOf(NorthSouthEdgeNeighbouringNodeCrossingsCounter.java:178)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.NorthSouthEdgeNeighbouringNodeCrossingsCounter.haveDifferentOrigins(NorthSouthEdgeNeighbouringNodeCrossingsCounter.java:158)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.NorthSouthEdgeNeighbouringNodeCrossingsCounter.processIfTwoNorthSouthNodes(NorthSouthEdgeNeighbouringNodeCrossingsCounter.java:91)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.NorthSouthEdgeNeighbouringNodeCrossingsCounter.countCrossings(NorthSouthEdgeNeighbouringNodeCrossingsCounter.java:83)
```

```
algorithm: layered
elk.direction: DOWN
//greedySwitch.type: OFF

node gen_node_1 {
	layout [ size: 1368.7118072509766, 160.52679443359375 ]
	portConstraints: FIXED_POS
	port gen_node_1_in {
		layout [ position: 80.26339721679688, -20 ]
	}
	port gen_node_1_yes {
		layout [ position: 80.26339721679688, 180.52679443359375 ]
	}
	port gen_node_1_no {
		layout [ position: 180.52679443359375, 80.26339721679688 ]
	}
	port gen_node_3_in {
		layout [ position: 360.7901916503906, -20 ]
	}
	port gen_node_3_yes {
		layout [ position: 360.7901916503906, 180.52679443359375 ]
	}
	port gen_node_3_no {
		layout [ position: 461.0535888671875, 80.26339721679688 ]
	}
	port gen_node_5_in {
		layout [ position: 641.3169860839844, -20 ]
	}
	port gen_node_5_yes {
		layout [ position: 641.3169860839844, 180.52679443359375 ]
	}
	port gen_node_5_no {
		layout [ position: 741.5803833007812, 80.26339721679688 ]
	}
	port gen_node_7_in {
		layout [ position: 921.8437805175781, -20 ]
	}
	port gen_node_7_yes {
		layout [ position: 921.8437805175781, 180.52679443359375 ]
	}
	port gen_node_7_no {
		layout [ position: 1022.107177734375, 80.26339721679688 ]
	}
	port gen_node_9_in {
		layout [ position: 1245.4094924926758, 29.945755004882812 ]
	}
	port gen_node_9_out {
		layout [ position: 1245.4094924926758, 130.58103942871094 ]
	}
}
node action_1 {
	layout [
		position: 268.9610824584961, 32
		size: 246.60462951660156, 60.635284423828125
	]
	portConstraints: FIXED_POS
	port action_1_in {
		layout [ position: 123.30231475830078, -20 ]
	}
	port action_1_out {
		layout [ position: 123.30231475830078, 80.63528442382812 ]
	}
}
edge gen_link_2: action_1.action_1_out -> gen_node_1.gen_node_1_in
edge gen_link_4: gen_node_1.gen_node_1_no -> gen_node_1.gen_node_3_in
edge gen_link_6: gen_node_1.gen_node_3_no -> gen_node_1.gen_node_5_in
edge gen_link_8: gen_node_1.gen_node_5_no -> gen_node_1.gen_node_7_in
edge gen_link_10: gen_node_1.gen_node_7_no -> gen_node_1.gen_node_9_in
```

**Comment by soerendomroes** [comment]
I get a IndexOutOfBoundsException instead:
```
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at org.eclipse.elk.alg.layered.p3order.counting.BinaryIndexedTree.rank(BinaryIndexedTree.java:68)
	at org.eclipse.elk.alg.layered.p3order.counting.CrossingsCounter.countCrossingsOnPorts(CrossingsCounter.java:367)
	at org.eclipse.elk.alg.layered.p3order.counting.CrossingsCounter.countCrossingsBetweenLayers(CrossingsCounter.java:166)
	at org.eclipse.elk.alg.layered.p3order.counting.AllCrossingsCounter.countCrossingsAt(AllCrossingsCounter.java:79)
	at org.eclipse.elk.alg.layered.p3order.counting.AllCrossingsCounter.countAllCrossings(AllCrossingsCounter.java:64)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.countCurrentNumberOfCrossings(LayerSweepCrossingMinimizer.java:230)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsWithCounter(LayerSweepCrossingMinimizer.java:201)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.compareDifferentRandomizedLayouts(LayerSweepCrossingMinimizer.java:185)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:143)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:121)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:592)
	at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:144)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:57)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:725)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:656)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:403)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:235)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by uruuru** [comment]
I'm not getting any exception anymore. However, the layout seems odd:
![image](https://user-images.githubusercontent.com/7552459/79244386-267aa000-7e77-11ea-9402-3562b0033418.png)

@le-cds maybe related to the other issues with invalid positions of hierarchical nodes? Also the selfloops are odd as well.

**Comment by le-cds** [comment]
> I'd say the layout seems fine then. And as I'm not getting any exception, I'd say we close it until somebody encounters it again.

Agreed.
