### ISSUE TITLE
Exception when combining Splines, Hierarchy, Self-Loops and some more stuff

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#352]
Please have a look at the following elk graph:
```
elk.direction: RIGHT
hierarchyHandling: INCLUDE_CHILDREN
edgeRouting: SPLINES

node N1

node N2 {
	node M1
	node M2 {
		port P1
		port P2
		port P3
		port P4
	}
	node M3
	
	edge M2.P1 -> M3 {
		label "1"
	}
	edge M2.P2 -> M1
	edge M3 -> M2.P4
	edge M3 -> M1
}
node N3
node N4

edge N1 -> N2.M2.P3
edge N2 -> N2
edge N2 -> N3
edge N2 -> N4
edge N2.M1 -> N3
edge N2.M1 -> N4
edge N3 -> N4
```

With orthogonal edges it creates this drawing
![splinehierarchyselfloop](https://user-images.githubusercontent.com/3796429/42032652-8e6b75ba-7ada-11e8-864c-2be89957924d.png)

However, with splines the following stack trace is generated:
```
!ENTRY org.eclipse.elk.core.service 4 0 2018-06-28 13:50:42.205
!MESSAGE Failed to perform diagram layout.
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: 4
	at org.eclipse.elk.alg.layered.p3order.counting.BinaryIndexedTree.rank(BinaryIndexedTree.java:68)
	at org.eclipse.elk.alg.layered.p3order.counting.CrossingsCounter.countCrossingsOnPorts(CrossingsCounter.java:367)
	at org.eclipse.elk.alg.layered.p3order.counting.CrossingsCounter.countCrossingsBetweenLayers(CrossingsCounter.java:166)
	at org.eclipse.elk.alg.layered.p3order.counting.AllCrossingsCounter.countCrossingsAt(AllCrossingsCounter.java:79)
	at org.eclipse.elk.alg.layered.p3order.counting.AllCrossingsCounter.countAllCrossings(AllCrossingsCounter.java:64)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.countCurrentNumberOfCrossings(LayerSweepCrossingMinimizer.java:230)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsWithCounter(LayerSweepCrossingMinimizer.java:213)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.compareDifferentRandomizedLayouts(LayerSweepCrossingMinimizer.java:185)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.lambda$1(LayerSweepCrossingMinimizer.java:131)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:143)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:121)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:241)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:182)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:58)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:222)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:197)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:76)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:718)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:650)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:400)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by uruuru** [comment]
First guess: related to dummy nodes created for handling the splines. If I'm not able to look at it earlier, @le-cds should look at it when he integrates the new spline self loop functionality.

**Comment by spoenemann** [comment]
The example can be reduced to this:

```
elk.direction: RIGHT
hierarchyHandling: INCLUDE_CHILDREN
//edgeRouting: SPLINES

node N2 {
	node M1 {
		layout [size: 30, 30]
	}
}
node N3 {
	layout [size: 30, 30]
}

edge N2 -> N2
edge N2 -> N3
edge N2.M1 -> N3
```

The exception mentioned by @le-cds occurs both with orthogonal routing and with splines.
