### ISSUE TITLE
 NULL pointer when opening sirius diagram firstly

### ISSUE THREAD

**Issue by penghzhang** [eclipse/elk#361]
I have integrated ELK 0.4.1 into eclipse(neon)， when I open a diagram in sirius editor, there an NullPointerException occurs as follows:

java.lang.NullPointerException
at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.transformExternalPort(ElkGraphImporter.java:631)
at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.importGraph(ElkGraphImporter.java:97)
at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:34)
at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:1)
at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:53)
at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:222)
at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:197)
at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:76)
at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:718)
at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:650)
at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:400)
at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)

**Comment by le-cds** [comment]
Please direct this issue to the Sirius project. They have done a lot to integrate ELK with Sirius over the past few months and would thus be the perfect people to bring this up with. :)
