### ISSUE TITLE
NullPointerException in ElkGraphImporter

### ISSUE THREAD

**Issue by nicholaskong** [eclipse/elk#372]
[https://www.eclipse.org/forums/index.php/t/1094868/](url)

When I use ELK Layered Algorithm in Sirius6.0 , there is a NullPointerException occur in ElkGraphImporter(603) (ELK version v0.3)

` dummy.setProperty(LayeredOptions.SPACING_LABEL_PORT,
                elkgraph.getParent().getProperty(LayeredOptions.SPACING_LABEL_PORT));`

In that time elkgraph.getParent() == null;

`Caused by: java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.transformExternalPort(ElkGraphImporter.java:603)
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.importGraph(ElkGraphImporter.java:94)
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:34)
	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:1)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:53)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
	at org.eclipse.sirius.diagram.elk.ElkDiagramLayoutConnector.layout(ElkDiagramLayoutConnector.java:1167)
	at org.eclipse.sirius.diagram.elk.ELKLayoutNodeProvider.layoutEditParts(ELKLayoutNodeProvider.java:37)
	at org.eclipse.sirius.diagram.ui.tools.internal.layout.provider.ArrangeSelectionLayoutProvider.lauchPrimaryArrangeAll(ArrangeSelectionLayoutProvider.java:255)
	at org.eclipse.sirius.diagram.ui.tools.internal.layout.provider.ArrangeSelectionLayoutProvider.layoutEditParts(ArrangeSelectionLayoutProvider.java:171)
	at org.eclipse.sirius.diagram.ui.tools.api.layout.provider.AbstractLayoutProvider.getCommandFromDiagramLayoutProvider(AbstractLayoutProvider.java:168)
	at org.eclipse.sirius.diagram.ui.tools.api.layout.provider.AbstractLayoutProvider.layoutEditParts(AbstractLayoutProvider.java:117)
	at org.eclipse.gmf.runtime.diagram.ui.services.layout.AbstractLayoutEditPartProvider.layoutLayoutNodes(AbstractLayoutEditPartProvider.java:69)
	at org.eclipse.gmf.runtime.diagram.ui.internal.services.layout.LayoutNodesOperation.execute(LayoutNodesOperation.java:74)
	at org.eclipse.gmf.runtime.common.core.service.ExecutionStrategy$1.execute(ExecutionStrategy.java:70)
	at org.eclipse.gmf.runtime.common.core.service.Service.execute(Service.java:651)
	at org.eclipse.gmf.runtime.diagram.ui.services.layout.LayoutService.execute(LayoutService.java:66)
	at org.eclipse.gmf.runtime.diagram.ui.services.layout.LayoutService.layoutLayoutNodes(LayoutService.java:299)
	at org.eclipse.gmf.runtime.diagram.ui.commands.ArrangeCommand.getCommandForExecution(ArrangeCommand.java:124)
	at org.eclipse.gmf.runtime.diagram.ui.commands.ArrangeCommand.doExecuteWithResult(ArrangeCommand.java:93)
	at org.eclipse.gmf.runtime.emf.commands.core.command.AbstractTransactionalCommand.doExecute(AbstractTransactionalCommand.java:247)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.emf.workspace.CompositeEMFOperation.doExecute(CompositeEMFOperation.java:217)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
	at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
	at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
	at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
	at org.eclipse.sirius.diagram.ui.tools.internal.commands.WrappingCommandIgnoringAffectedFiles.execute(WrappingCommandIgnoringAffectedFiles.java:123)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	... 41 more
`

**Comment by le-cds** [comment]
I bet what happens is that the top node (the one the represents the graph to be laid out) has ports. This is not allowed. In a way, the top node represents the drawing area the actual graph will be drawn on, and while it can have a position and a size as well as children, it cannot itself have ports.

I believe that this is a problem in the way the Sirius developers connect to ELK and thus should be reported to the Sirius team.

**Comment by nicholaskong** [comment]
Yes, Christoph, you are right. The top node has ports, these ports also has some connector.
I can not attach image into GitHub, I attached it into this part:https://www.eclipse.org/forums/index.php/t/1094868/
I also can provide the sample model and meta-model for this issue.

**Comment by nicholaskong** [comment]
Thanks you can respond this problem. 
But as I know this kind of is existing in circuit design, because our customer wants this kind of display.
Actually in ELK V0.2.2, we can use layer algorithm to process this model.

**Comment by pcdavid** [comment]
@nicholaskong has opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=538373 to handle the issue on the Sirius side, this can probably be closed.

**Comment by le-cds** [comment]
> this can probably be closed.

I will do that. Feel free to reopen it if there's anything we should be doing.

**Comment by nicholaskong** [comment]
@le-cds @pcdavid  I also find an other integration problem.
I also add it into https://www.eclipse.org/forums/index.php/m/1794531/#msg_1794531
This problem not only shown Sirius(6.0) & ELK(0.3), but also shown Sirius(4.1.3) & ELK(0.2.2), so I think this problem may a defect of Sirius & ELK integration.
