### ISSUE TITLE
NPE when using MERGE_EDGES and self loops

### ISSUE THREAD

**Issue by dhuebner** [eclipse/elk#382]
Version: 0.5.0-Snapshot 
Layout: Layered

```
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeOrder(SelfLoopComponentDependencyGraphCalculator.java:242)
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeOrder(SelfLoopComponentDependencyGraphCalculator.java:302)
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeDependecies(SelfLoopComponentDependencyGraphCalculator.java:200)
	at org.eclipse.elk.alg.layered.intermediate.SelfLoopPlacer.process(SelfLoopPlacer.java:85)
	at org.eclipse.elk.alg.layered.intermediate.SelfLoopPlacer.process(SelfLoopPlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:600)
	at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:144)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:58)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
....
```

**Comment by uruuru** [comment]
That's in the new self loop code. @le-cds, any ideas?

Maybe an unassigned port side: 
```
 if (targetPort.getPortSide() != side && targetIndexAllPorts < portIndex) {
```

@dhuebner can you share a graph to reproduce the problem or at least give a hint regarding the graph's structure?

**Comment by le-cds** [comment]
A simple graph that reproduces this issue would indeed be helpful. :)

**Comment by lredor** [comment]
I have a reproduction case for this NPE (or at least with a similar stack). I tried to minimize my case. The graph, without layout, is like this:
![Sample With NPE](https://user-images.githubusercontent.com/1825882/57758020-0c7c8e80-76f7-11e9-9933-67e5b4b71b2a.png)

Steps to reproduce:
* Import the graph file "Sample With NPE.elkg" in your workspace from [Sample With NPE.zip](https://github.com/eclipse/elk/files/3181478/Sample.With.NPE.zip)
* Open the Layout Graph view
* Load the graph file in this view
* Result: The following NPE is thrown:
```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeOrder(SelfLoopComponentDependencyGraphCalculator.java:242)
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeDependecies(SelfLoopComponentDependencyGraphCalculator.java:200)
	at org.eclipse.elk.alg.layered.intermediate.SelfLoopPlacer.process(SelfLoopPlacer.java:85)
	at org.eclipse.elk.alg.layered.intermediate.SelfLoopPlacer.process(SelfLoopPlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:244)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:186)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:54)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.debug.views.graph.LoadGraphAction.layout(LoadGraphAction.java:98)
	at org.eclipse.elk.core.debug.views.graph.LoadGraphAction.run(LoadGraphAction.java:81)
	...
```

**Comment by spoenemann** [comment]
This might have been fixed in the meantime, see https://github.com/eclipse/elk/issues/417#issuecomment-494451351

**Comment by le-cds** [comment]
@lredor thanks for the test case. The exception is not thrown anymore. :)
