### ISSUE TITLE
Hierarchical graph with self-loops has inconsistent edge routing

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#413]
```
node N1 {
	portConstraints: FIXED_SIDE
	port P1 {
		layout [ size: 15, 20 ]
		^port.side: WEST
	}
	port P2 {
		layout [ size: 15, 20 ]
		^port.side: WEST
	}
	port P3 {
		layout [ size: 15, 20 ]
		^port.side: EAST
	}
	node N2 {
		layout [ size: 20, 20 ]
	}
	edge E2: P1 -> N2
}
edge E1: N1.P3 -> N1.P2
```
leads to
![Screenshot 2019-04-15 at 09 39 24](https://user-images.githubusercontent.com/4067210/56114869-622c1280-5f62-11e9-8065-ce353ce03eac.png)

The position of P1 is inconsistent with the routing of E2.

**Comment by spoenemann** [comment]
If I add the option
```
hierarchyHandling: INCLUDE_CHILDREN
```
I get

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKAligner.verticalAlignment(BKAligner.java:145)
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKNodePlacer.process(BKNodePlacer.java:223)
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKNodePlacer.process(BKNodePlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:244)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:186)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:54)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:718)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:650)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:400)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
