### ISSUE TITLE
AIOOBE in BKNodePlacer

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#415]
```
hierarchyHandling: INCLUDE_CHILDREN
node N1 {
	port P1
	port P2
	port P3
	node N2 {
		layout [ size: 20, 20 ]
	}
	edge E2: P1 -> N2
}
edge E1: N1.P3 -> N1.P2
```

leads to

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKAligner.verticalAlignment(BKAligner.java:145)
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKNodePlacer.process(BKNodePlacer.java:223)
	at org.eclipse.elk.alg.layered.p4nodes.bk.BKNodePlacer.process(BKNodePlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.hierarchicalLayout(ElkLayered.java:244)
	at org.eclipse.elk.alg.layered.ElkLayered.doCompoundLayout(ElkLayered.java:186)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:54)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:718)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:650)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:400)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by le-cds** [comment]
@uruuru Do you have an idea?

**Comment by uruuru** [comment]
Not off the top of my head. But given that it happens for such a small example I'll try to find time and look at it.

**Comment by le-cds** [comment]
@uruuru Indeed. It seems like the self loop's ports are not properly placed while the node's insides are being laid out. Works perfectly fine without hierarchical layout. I'll take a look.

**Comment by le-cds** [comment]
In fact, I'll open another ticket for that issue (#552) and close this one.
