### ISSUE TITLE
NPE in SelfLoopComponentDependencyGraphCalculator

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#417]
```
node N1 {
	port P1
	port P2
	port P3
	port P4
	port P5
	port P6
}
node N2 {
	port P7
}
edge E1: N1.P4 -> N1.P1
edge E2: N1.P5 -> N1.P2
edge E3: N1.P6 -> N1.P3
edge E4: N1.P6 -> N2.P7
```

leads to

```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeOrder(SelfLoopComponentDependencyGraphCalculator.java:242)
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeOrder(SelfLoopComponentDependencyGraphCalculator.java:302)
	at org.eclipse.elk.alg.layered.p5edges.loops.calculators.SelfLoopComponentDependencyGraphCalculator.calculateEdgeDependecies(SelfLoopComponentDependencyGraphCalculator.java:200)
	at org.eclipse.elk.alg.layered.intermediate.SelfLoopPlacer.process(SelfLoopPlacer.java:85)
	at org.eclipse.elk.alg.layered.intermediate.SelfLoopPlacer.process(SelfLoopPlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:592)
	at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:144)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:57)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:718)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:650)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:400)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lredor** [comment]
This fix seems to also fixes https://github.com/eclipse/elk/issues/382. At least, it fixes the [use case](https://github.com/eclipse/elk/issues/382#issuecomment-492548068) that I added.
