### ISSUE TITLE
Layered Layout: Crossing minimization causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/elk#463]
On some specific big graph, the crossing minimazation causes an  ArrayIndexOutOfBoundsException. Here is the stacktrace:

```
java.lang.ArrayIndexOutOfBoundsException: Index 68 out of bounds for length 68
	at org.eclipse.elk.alg.layered.p3order.counting.BinaryIndexedTree.add(BinaryIndexedTree.java:49)
	at org.eclipse.elk.alg.layered.p3order.counting.CrossingsCounter.countInLayerCrossingsOnPorts(CrossingsCounter.java:400)
	at org.eclipse.elk.alg.layered.p3order.counting.CrossingsCounter.countInLayerCrossingsOnSide(CrossingsCounter.java:180)
	at org.eclipse.elk.alg.layered.p3order.counting.AllCrossingsCounter.countCrossingsAt(AllCrossingsCounter.java:76)
	at org.eclipse.elk.alg.layered.p3order.counting.AllCrossingsCounter.countAllCrossings(AllCrossingsCounter.java:64)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.countCurrentNumberOfCrossings(LayerSweepCrossingMinimizer.java:230)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsWithCounter(LayerSweepCrossingMinimizer.java:213)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.compareDifferentRandomizedLayouts(LayerSweepCrossingMinimizer.java:185)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:143)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:121)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:578)
	at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:152)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:57)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:198)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:198)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:725)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:656)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:403)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:235)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
... and the debug information generated during the layout attempt:
[1571310087020dm-Diagram_layout_engine.zip](https://github.com/eclipse/elk/files/3738886/1571310087020dm-Diagram_layout_engine.zip)

With this big example it may be hard to pinpoint the exact problem, this issue is just for documentation of this issue if somebody comes across it as well and finds a smaller example where this happens.

**Comment by NiklasRentzCAU** [comment]
I found a much smaller example as I was continuing to get this error:
[1571320078446ng-Diagram_layout_engine.zip](https://github.com/eclipse/elk/files/3739630/1571320078446ng-Diagram_layout_engine.zip)
This error only occured when there was at least one node with a self-loop going from one of its east ports going to its own west port with some other edges around that node.

**Comment by le-cds** [comment]
The new self loop code introduced with release 0.6.0 fixes this issue. To be sure, I added a test that runs layout on this graph and ensures that no exceptions get thrown around.
