### ISSUE TITLE
Exceptions during maven test execution

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#540]
During maven build on hudson, a couple of exceptions occur during test execution. 

Three questions are to be answered for all types of exceptions:
1) one would expect that this yields the test stage to fail (it does not, however)
  --> fixed by #543
2) the exceptions do not occur in a regular Eclipse-setup (they do during Eclipse-based JUnit-Test execution though)
3) the nullpoint exceptions happen for diagrams that have no edge labels at all - and thus shouldn't run the corresponding code
  *Answer:* The test creates dummy labels for all edges without any. 

a) **java.lang.NullPointerException**
--> Issue is tracked in #541
During LabelSideSelectorTest
```
algorithm(org.eclipse.elk.layered) defaults(nodes, ports, edges) configMethod(configurator) graphFile(/home/hudson/genie.elk/.jenkins/jobs/IntegrationNightly/workspace/elk-models/realworld/ptolemy/flattened/ptango_cookies_Cookies.elkt)
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.intermediate.EndLabelSorter$1.compare(EndLabelSorter.java:201)
	at org.eclipse.elk.alg.layered.intermediate.EndLabelSorter$1.compare(EndLabelSorter.java:1)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at org.eclipse.elk.alg.layered.intermediate.EndLabelSorter.sort(EndLabelSorter.java:140)
	at org.eclipse.elk.alg.layered.intermediate.EndLabelSorter.processNode(EndLabelSorter.java:84)
	at org.eclipse.elk.alg.layered.intermediate.EndLabelSorter.lambda$2(EndLabelSorter.java:61)
```

b) **java.lang.IllegalStateException**
--> Issue is tracked in #542, fixed for the moment by adjusting the test case to not enforce the erroneous behavior. 
During EdgeAndLayerConstraintEdgeReverserTest
```
algorithm(org.eclipse.elk.layered) defaults() graphFile(/home/hudson/genie.elk/.jenkins/jobs/IntegrationNightly/workspace/elk-models/tests/layered/compaction_oned/selfloop/selfloop_orthogonal.elkt)
java.lang.IllegalStateException: Invalid hitboxes for scanline constraint calculation.
	at org.eclipse.elk.alg.common.compaction.oned.ScanlineConstraintCalculator$ConstraintsScanlineHandler.insert(ScanlineConstraintCalculator.java:175)
	at org.eclipse.elk.alg.common.compaction.oned.ScanlineConstraintCalculator$ConstraintsScanlineHandler.handle(ScanlineConstraintCalculator.java:165)
	at org.eclipse.elk.alg.common.compaction.oned.ScanlineConstraintCalculator$ConstraintsScanlineHandler.handle(ScanlineConstraintCalculator.java:1)
	at org.eclipse.elk.alg.common.compaction.Scanline.go(Scanline.java:83)
	at org.eclipse.elk.alg.common.compaction.Scanline.execute(Scanline.java:56)
	at org.eclipse.elk.alg.common.compaction.Scanline.execute(Scanline.java:72)
	at org.eclipse.elk.alg.common.compaction.oned.ScanlineConstraintCalculator.sweep(ScanlineConstraintCalculator.java:73)
	at org.eclipse.elk.alg.layered.intermediate.compaction.EdgeAwareScanlineConstraintCalculation.calculateForOrthogonal(EdgeAwareScanlineConstraintCalculation.java:188)
	at org.eclipse.elk.alg.layered.intermediate.compaction.EdgeAwareScanlineConstraintCalculation.calculateConstraints(EdgeAwareScanlineConstraintCalculation.java:57)
```

c) **java.lang.AssertionError**
--> Fixed by #543
During BasicLayerAssignmentTest
```
java.lang.AssertionError: Port positions must be integral
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.transformEdge(NetworkSimplexPlacer.java:592)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.lambda$5(NetworkSimplexPlacer.java:568)
```

**Comment by uruuru** [comment]
All points have been clarified and either have already been fixed or are tracked as part of other tickets.
