### ISSUE TITLE
Layered Polyline NPE

### ISSUE THREAD

**Issue by shean42** [eclipse/elk#587]
While playing around some more with polyline routing a NPE case came up ([live view](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYEw5sBKD2CuAuBLAdmAXAAgAoHkAyAmngJIByAogFCXLQjAbICMlA3pRhgA7QBO8GAIYdufAQCMRAG0HjgUjACJmiygF9qteowBMbET35CDYjJM4y5C5TtUaadBsgDM+zoYHD3p8xkvylFztNR0YAFjdRIy8oiWlZAOUw4IdtZABWSI9jbyNff2sMlK0nADYs0xjs-ITC0pTQCEYmADpBDABaAD5dFslGpx02zp7kML7KAfDh7sZnCamXGdH0hfAnVfbZ5FK1pp3l3skgA)).

Thought you might be interested :-)

**Comment by uruuru** [comment]
Also happens for `SPLINES`. 

```
java.lang.NullPointerException
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.addAdjacencyOf(BetweenLayerEdgeTwoNodeCrossingsCounter.java:278)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.iterateTroughEdgesCollectingAdjacencies(BetweenLayerEdgeTwoNodeCrossingsCounter.java:260)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.getAdjacenciesSortedByPosition(BetweenLayerEdgeTwoNodeCrossingsCounter.java:249)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.<init>(BetweenLayerEdgeTwoNodeCrossingsCounter.java:245)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter.getAdjacencyFor(BetweenLayerEdgeTwoNodeCrossingsCounter.java:167)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter.addWesternCrossings(BetweenLayerEdgeTwoNodeCrossingsCounter.java:176)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter.countBothSideCrossings(BetweenLayerEdgeTwoNodeCrossingsCounter.java:140)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.CrossingMatrixFiller.fillCrossingMatrix(CrossingMatrixFiller.java:67)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.CrossingMatrixFiller.getCrossingMatrixEntry(CrossingMatrixFiller.java:50)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.SwitchDecider.doesSwitchReduceCrossings(SwitchDecider.java:135)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.switchIfImproves(GreedySwitchHeuristic.java:115)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.sweepDownwardInLayer(GreedySwitchHeuristic.java:107)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.continueSwitchingUntilNoImprovementInLayer(GreedySwitchHeuristic.java:95)
	at org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.minimizeCrossings(GreedySwitchHeuristic.java:64)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.sweepReducingCrossings(LayerSweepCrossingMinimizer.java:251)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsNoCounter(LayerSweepCrossingMinimizer.java:167)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:142)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:120)
	at org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:593)
```

**Comment by lredor** [comment]
For information, I have noticed the same stacktrace with the [following sample](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBA4gRgFABswE8D2BXALjAbRgGcBLALwFMAuGBAJgA4BWAGhgDYAWDmAXSTEIYAMakAdsAB0ETCFwAFObloIA7FIAMScZgAmlAMoVKUkZnHFc4CbmK0ARAQUB5AEoAVQ+wByLgCIAogD6ADIAggBCgaHeMACyAJI+ifEAqvHBhokAWoF8DkhQpJTgICJQ6AASYOJ6KBLAtMkAwqFpQcEtVYmh-m6BPkhgKMBypLhQALa0ctKUIg0QxKaUKADWUmjopZR6gsJiklJ7wJQ++pSRlLgA7pSU4qEYpfYw9JpaSKeUbji4jVo7g8VRccBcPnCoW+ejOzwARmtiFIyAZDGsFgCLLRDPFwp5gmkFDpLgo0CJKFNHrgpPDNgAzUgADz24QawHEVPEKhgbkScCqHn8LgA6kNdM8sHhaPSRisSQYYC0LLgwBJSjAAN5IACQ23+hF1OtkZCx4lo9C4bDo9HoRrIVFoamYjHYAGYuIxdQIdUJRI0ZMolPJVBptDrdGiTGYLFYbNy3k5XJ44n5OhForF2EkUulMtk8gVdcVSmBypUanUGpJmj42h0Qt1ev1BrrI0Zo1MJKQptgZjAHAAKBBurSsejMLQASkKvsOAZ+FwM1zuDyeLxAbw+Xx1Pz+eEBMGBoPBkOhu9hlARSJRpDRGJEZpxeIJRLbpPJlOptIZzNZ7M5alaD5AUhVFIZjWUa8UGRCBPy5HknCLPUwERFAYFCBBHGVbk1XEUoHC1I19TwQ0dXIk0JlIbEYDdZh6HYZgjV9ExaGYDh2HUI0fQjS5oNg+CgIHAgqi6QYPECNx2AANWCDwXAUdhkmyIJkIAX11WR5BgBQECI8iSPwAhmMop8YAAWgYdhbTdZiHRod5NGs8MdR4uYTkWUhllWDYpAAPS0ml4TkAwQBcel6RWHlzMYHcULQjD6EcRJxAgPAEEI7VyJQqUjOYyDTWo80LNdd5kGyljHVoji6DUZieI0nVGsCnT6H0nKDWM7LTKKp16Ocpjsvsi0nMc7ijXchYlhWE5fIC5RaRC0pwsim5aBiuK0AS0I3UcFw8DS3AMvajrSK67rMEKmjLNHa16HKobWJgLg1E4ursoa3VmuUHS3XawyyIoy6qJo50GPeABOWzHqqj5nPG8jJs87zZs2eb5EWkBQpWqL1tilytrWDCuD2g68HoTLmIB86gau4qbqkO6HvI4bnte2r6qNRrvu0hQuH+jBOpM4GzMs8H6A4d6WaeuGxvItyQHmZGZrWNHAsx7GItxkrNtQonQmYZLuX2o7Key6n8p666EAQazmcqhyuHBriPq5r7NJ+hRmAF3LAYKkH6as2ibbsmXRo+BGdSR6afLVhbgqx5atbWnWCb19DQg4I3cBNimTotiqrcD22yvy1mnbeznyO599FRw1V1RAUJSCsNqstOvKLrp1QJc4z1Q9hhBRoYCHI79I5pEC4MeXUOL22MKgY0saw8LsRxnGBVMAhCDMYjiHNUgyLJcnyWcdRLMoKmqWp6kPVp2k6Js+gGCDeKjReu3EHs+0cYdJycp204z6BX4jIQS3J17ITnP6Y4i5LgrnuI8SUrwRpxT3P8Q8x4wQQihEaH4oDURGAfGZXE+IPCEmJORdsZJRBfm5D+KQjIWR6DZKQDkCFgL8kFMKMUeDfLCD0HoQ8ThcCYAgAAXjDKwFAlB6S4HEf-VgwVcCiKmOIhAY4QBsKgPI-+UDx4BnbEuBynwXLtlAQIoRNZhKiIkaY6Rsj5H2OUao8R9itHAB0W4rQUCRAgEumQSQ8RuxdnIGAM0KIV64EoMAdAtYJJuHCC0DwiRpKBGIunDCjBsIqjwqUZurczYGUFmdS2IteqcGtINGGDlGDOylq5Zi5j04CVoRw4SokWjiUkjJOSCklI+BUqfN2QNea8Hbh3P2-tRZB2dGXMO8NXbZWjl5FWc11YJ01qtaK+MqaZNCBDI2h1joTMmTTWmAc8Z23yg7WgboaouyWdXEZkFeZqHziUzuXdLmOS4IxBptzHKLPlsxFZKNVb+Q2UtMKycdlxXivrIepNcDHKKcU325zpkVIZkzG55d2aPJBdlRqTUjQtQUIwD5GKynd1+ewCGXB5mw3Di5RpyzFYeRjqjSF8doU4xThtVlhMM422RYdPOpyC6F3KdbW61yKqApepXCqPFSXPLVe2JUuTG4FNwH9duUqsU0U9OzegdEB4OXuqNCGdoiXQInoGeQ09Qxz0uAvUw5hl7xjXsJZMXhfDbzCFEPe2ZkiH3zCfKBF8yxX0rLfax98GxdB6M-VsVC3WdhCT-Acf8xyAM0DOMlUEWlgLaUJJCZ8DGwMvMYhBa5kGblQS5dBB5rFYNPLg8i+CS2EPRDIx8FTSGvkoW-SgNCKQIQYUw-8bDAIQN5FwsCvCu38LAII4RBBbGSLHDIuRCixwuMwGojRTkPFeL0ZW+cxwjGXFoKYo0zS0KwTXVYpoNixHeKcrupxB7MAqKPZ+1gZ6f2aF8f44ggTgDBK-qE8JRVIngGibE+JkkkkpLSRk7aI4cm4R1S3PVaLDVGuKhwKpTLan1KrumgwFjwGIREmJHwCTenyUUjAZSiRVJnxJeSiGVKhbStpWLf55GRrArZYjDlU1Vmxx5RjTZSdtl43hcKjCCASYDgkKik6ZyblFyuaXBVrN7nKqeWq8z5Kh78dKYJn5Hw-kwGYAC1mssI5mbBWsuO8m+WwuU0K-ZCBDYDhNtpyVnypnEfWiORm8qKr4tM3a8zNdR1atw-hJu+G9IGvCzTfTNoS4egtRaBAEN6W2ok1WyeQZlAurMRmxenq4yr0TBvFMAb0zBqzAkMNeZj6FjPtG8s18qx3zrA-RsKaWyv3npmmD2ahyBbzfQIBRb5C0bLfOit9or3zBrfAm4iD1w7EbY5NBl59wAjbZ4E8ODzwXjhD2u8RD+0kJfOQt81Gx10anX+FhAF2kgW4eBPhmxLEbq3VI79+6nKHuPZo7RuifGXpgdIG9Bg72upoyWsH1iREfvsVD5xf7XHuIR5+sDATGjQZ7BQODFgEPhJiXE9jTHUPJNSek4pWG1A4Ybul3VJy9nUts2ZDgpXHOiZgHUhLqrH03jght+jnTulSRgLJVjAyhlQJ457G21mvkXJmeDJzkvXOstVR52T6Mgo+aU6nPZWHskDhSoLiqRHIt0Bi4ZuLT11AJYk0l1b+BdJtyFwJ75Zl7puhEz75l4mLdSeVlbqFicYV28FQ7xFhzgvkzRbphVeXzIOfunimWpVCUB5Jcln4MBAhYVS3z-J+HRwKD4+ZAAfA3vJGXW5SApT7cPvpMRFVr4YPS5yrBlh5C9a0bpNDla7XUO5XBxcTgXzqREdQ3hO2j7RefMAAA+z0zXWXolRhWSsuUQr8j8KQkxSAiHWPhCDFodyNRr4EJKXe8O94ULwDvOkWWGSwuLMw+Fgo+bUE+qoIYdA6m1kbo0M2UjwegTo8BiBEmF+nKMm3KN+l4d+xQj+z+W4b+uoH+u03+-O+Gy2Cg7yABCgoe6Kg+KwA64BgQhgf0UBU+y+q+gW+UyBfU4svBTymB0m4Kc0t+9+hBlAL+7wus20POwkPwBQ+uUyeWLo5eUMkubo5eDSqq3aT6paE6QkXSrObgIy7+l4teQW9c3euqLeVmdB+qwBTBYB4go+3snBMBagQ87o8+fBS+MAYMvh6BG+yBbwagboBW++R+ERUR6BPEIhSeOBEhBBT+0hxB4YGkGkH+GmNhjcfeekABeR6WfeDBUqzBZoo+-MNMk+MBwm7wCBzE-BgR3hds1SoRW+eMxeCBh+JUDm5kpGvRjAgW7AAx3sR+wxTM1SPoPoluyReBkhaRMhy22g2RlhgQWcFBpQfe3sRR2qJRfM+k5Rrho+vANR0B0UQcboJeSBAR9R9AagDSm+egbw5kEMs+90vRbxd0jxCMsxieV+4hCxqRRBr+qxMIZwteChxR2xhxexaWsJ3sWUxxLBbhbB7y5xXBFkQcDxDSzR9R1xzMzxrxI4Px7yR+N0HxD0Mxuocx1+KRD+SxGRSAGkQAA). Since the fix of [#608](https://github.com/eclipse/elk/issues/608) , this case is OK (but not the initial one). So the #608 has a side effect on the current issue. It seems that the changes line 263 is the cause of the change for my case: `firstSweep && !graph.lGraph().getProperty(InternalProperties.FIRST_TRY_WITH_INITIAL_ORDER)` instead of just `firstSweep`.

**Comment by lredor** [comment]
For the above use case, in ElkLive, if you switch to "0.6.1" version, the layout is OK.

**Comment by le-cds** [comment]
The problem seems to have been the condition under which inverted port processing was activated. In this case, there is in fact an inverted port, but our logic does not recognize that.
