### ISSUE TITLE
Consider model order breaks markCrossingEdges

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/elk#696]
Somehow `considerModelOrder` seems to break the crossing marking in the NetworkSimplexPlacer. No `EAST` edge is identified, but a `WEST` edge in the correspoding layer. 

```
INFO  r.klighd.lsp.KGraphDiagramGenerator  - Generating diagram for input: 'file:///home/nre/workspace/sctx/test.sctx'
java.util.NoSuchElementException
	at java.util.ArrayList$ListItr.previous(ArrayList.java:941)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.markCrossingEdges(NetworkSimplexPlacer.java:1334)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.lambda$29(NetworkSimplexPlacer.java:1300)
	at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:546)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.markEdgeCrossings(NetworkSimplexPlacer.java:1299)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.preferStraightEdges(NetworkSimplexPlacer.java:1023)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.process(NetworkSimplexPlacer.java:235)
	at org.eclipse.elk.alg.layered.p4nodes.NetworkSimplexPlacer.process(NetworkSimplexPlacer.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:606)
	at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:143)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:56)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:250)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:218)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:200)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:96)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:703)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:631)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:493)
	at de.cau.cs.kieler.klighd.LightDiagramServices.layoutDiagram(LightDiagramServices.java:259)
	at de.cau.cs.kieler.klighd.LightDiagramLayoutConfig.performLayout(LightDiagramLayoutConfig.java:410)
	at de.cau.cs.kieler.klighd.lsp.KGraphLayoutEngine.onlyLayoutOnKGraph(KGraphLayoutEngine.java:79)
	at de.cau.cs.kieler.klighd.lsp.KGraphLayoutEngine.layout(KGraphLayoutEngine.java:60)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.lambda$1(KGraphDiagramServer.java:385)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.lambda$1(AbstractLanguageServer.java:116)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.configureAndRun(AbstractLanguageServer.java:97)
	at de.cau.cs.kieler.language.server.LanguageServer.main(LanguageServer.java:44)
```

SCChart to reproduce:
```
scchart Test {
    input signal I
    output signal O

    region {
        initial state A
        if I do O go to B

        final state B
    }
}
```
Compile to C and view SCG.

**Comment by soerendomroes** [comment]
The problem occurs, since the `portSideIndices` list is sorted differently than list of ports, therefore `LNode.getPortSideView` returns the wrong node.
