### ISSUE TITLE
Problem setting up locally

### ISSUE THREAD

**Issue by saulshanabrook** [eclipse/elk#772]
I am following the steps to try to get set up [developing locally with Oomph](https://www.eclipse.org/elk/documentation/contributors/developmentworkflow/installingwithoomph.html) and hit an error, on the final step. It said `No repository found at No repository found at http://build.eclipse.org/modeling/elk/updates/nightly/`. The full log is below:

```
Executing bootstrap tasks
Java(TM) SE Runtime Environment 14.0.1+7
Product org.eclipse.products.epp.package.java.2021-09
Workspace /Users/saul/p/elk/ws
Project org.eclipse.elk.master
Bundle org.eclipse.oomph.setup 1.20.0.v20210601-0619, build=5141, branch=67b7b5642ad3a3c48e6c206588e5b85492209546
Bundle org.eclipse.oomph.setup.core 1.20.0.v20210601-0619, build=5141, branch=67b7b5642ad3a3c48e6c206588e5b85492209546
Bundle org.eclipse.oomph.setup.installer 1.21.0.v20210604-0646, build=5141, branch=67b7b5642ad3a3c48e6c206588e5b85492209546
Bundle org.eclipse.oomph.setup.p2 1.17.0.v20210601-0619, build=5141, branch=67b7b5642ad3a3c48e6c206588e5b85492209546
Performing Workspace /Users/saul/p/elk/ws
Performing P2 Director (Eclipse IDE for Java Developers (2021-09))
Offline = false
Mirrors = true
Resolving 32 requirements from 6 repositoriesto /Users/saul/p/elk/Eclipse.app/Contents/Eclipse
Requirement org.eclipse.equinox.p2.iu:org.eclipse.elk.sdk.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.emf.sdk.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.xtext.sdk.feature.group [2.20.0,2.21.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.sdk.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.preferences.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.workingsets.feature.group
Requirement org.eclipse.equinox.p2.iu:net.sf.eclipsecs.feature.group
Requirement org.eclipse.equinox.p2.iu:epp.package.java [4.21.0,5.0.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.21.0,5.0.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.21.0,5.0.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.buildship.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.epp.mpc.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jgit.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext.editors_feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.tips.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.tm.terminal.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.xml.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.pde.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.jdt.feature.group
Repository http://build.eclipse.org/modeling/elk/updates/nightly/
Repository http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.20.0
Repository https://rtsys.informatik.uni-kiel.de/~kieler/updatesite/checkstyle
Repository http://download.eclipse.org/technology/epp/packages/2021-09/202107141200
Repository http://download.eclipse.org/releases/2021-09/202107161000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Fetching p2.index from http://download.eclipse.org/releases/2021-09/202107161000/ (140B)
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/releases/2021-09/202107161000
Adding repository http://download.eclipse.org/technology/epp/packages/2021-09/202107141200
Fetching p2.index from http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.20.0/ (172B)
Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.20.0
Adding repository http://build.eclipse.org/modeling/elk/updates/nightly/
Fetching content.xml.xz from http://download.eclipse.org/releases/2021-09/202107161000/ (760.75kB)
Fetching content.jar from http://download.eclipse.org/technology/epp/packages/2021-09/202107141200/ (67.82kB)
Fetching content.xml.xz from http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.20.0/ (20.24kB)
Adding repository https://rtsys.informatik.uni-kiel.de/~kieler/updatesite/checkstyle
Fetching content.jar from https://rtsys.informatik.uni-kiel.de/~kieler/updatesite/checkstyle/ (28.29kB)
ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at http://build.eclipse.org/modeling/elk/updates/nightly/.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:397)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:367)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:258)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:495)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1578)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:434)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Took 3 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

Any tips? I am on Mac OS X 10.15.7 with Eclipse installer 1.21.0 Build 5141.

**Comment by uruuru** [comment]
I believe `build.eclipse.org` has been decomissioned.

IIRC, @le-cds migrated the build to deploy to `download.eclipse.org` a while ago. 

Could you check if replacing 
 * http://build.eclipse.org/modeling/elk/updates/nightly/
 * by https://download.eclipse.org/elk/updates/nightly/
 
helps? I can imagine that there are futher urls in the setup that would've to be adjusted.

**Comment by saulshanabrook** [comment]
Thanks for the tip! I updated the installer to `1.22.0`, but still the same error... I don't see anywhere to put in the URL unfortunately!

![](https://user-images.githubusercontent.com/1186124/128033460-a99ced59-71d2-41da-a532-ce0d0360c73b.png)

**Comment by uruuru** [comment]
https://github.com/eclipse/elk/blob/8d322003fe0c345b0e64af8867901b508a660122/setups/EclipseLayoutKernel.setup#L267
