### ISSUE TITLE
FIXED_SIDE and FIXED_POS ports throw exception when defined on hierarchical node of 2 levels of nesting

### ISSUE THREAD

**Issue by alexei-tilikin** [eclipse/elk#813]
Using the`layered` algo with elkjs.
The graph has deep nesting of nodes inside nodes.
Problem reproduces on `elkjs@0.7.1` and `elkjs@0.7.3-dev`

On level 2 `root.children[*].children[*].layoutData`, if I define the option
`'elk.portConstraints': 'FIXED_POS'` or `'elk.portConstraints': 'FIXED_ORDER'`,
elk will throw exception:
```
TypeError: Cannot read properties of null (reading 'x_0')
    at createExternalPortDummy (elk-worker.js:31762:1)
    at $transformHierarchyEdges (elk-worker.js:30937:1)
    at $transformHierarchyEdges (elk-worker.js:30927:1)
    at $process_1 (elk-worker.js:30774:1)
    at $doCompoundLayout (elk-worker.js:27705:1)
    at LayeredLayoutProvider.layout_2 [as layout] (elk-worker.js:28027:1)
    at $executeAlgorithm (elk-worker.js:61782:1)
    at $layoutRecursively (elk-worker.js:61872:1)
    at $layout_3 (elk-worker.js:61817:1)
    at layout_11 (elk-worker.js:74016:1)
    at Dispatcher.dispatch (elk-worker.js:73945:1)
    at Dispatcher.saveDispatch (elk-worker.js:73953:1)
    at elk-worker.js:73970:1
```

Here's the demo reproducing the problem:
https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oH1kCUDyGAqrIBpwoBjAC2gBtYAnAUwDtEwBtIiUCTqOJyAc2oB7AK4AHZACYCbTpDKUaDJqy5cOqrjHhJ+QscgCM0jZvlU6jJCpNqZNiFt71BsWsgAMx+5oDucAC6kTAYArO6E3pqktNB8pP7BEgDMdiYAvhGR6pHc2lDOrpJeOZB+sIHBYZkl0bHxiSk5Gaka2ZGOOgVuAOzF7aKC1P4Azsot9m05Djw6tLB8tAjEDP601IYIXcjdyAAKGGi4AJIAcn1TUGUVSAbVF1AAHsHh496QFACGAJ4i-hii-mggnooyQk3ukFoFAA1gA6AZDWHDOC0XgnA7YAAS5whULhCP8sOg9FcTxur3saQpGipFwAunc3lcgjcqtTZLU4gkbsl2bT7AyKe9vr9-oDgaCwOCNJCYbCugBlaAAL1osOIEv81A+xJGvAAsqcjvqAKr65AKo4ALQAojiZXj4R9YLBiXxeMx-IJRABeAAs4WodX8PoM4QARoJ-F6ALb+8IUWgAMxDYbp9tUsvxg38AGFNdrdZLIAAxI4ADRtABFkAcqza0BmuBT+TTUoKZZ8fsI-gCgSCmNKoI7FSq1RqQVqdfQ9TpDSdjWaLda7YzZI7RM7XfR3TpPd74-gg1zQxGo7HD4mU6f02vW2BmrYZTMSCs1oYcZACZLrK0hS-IXmRZlhnd8DAQAQRHEAw9gxWsTWwJtLgCFkwFuIUyTAABaMM100LtRT7CVB3ZLN4RzJEUV4BUMAQ7E8MzDcKOJUkmHcFtxkfEwh2mPJAIWJY33WcCth2fZDngxCGIcZlgmkx4mBwl43gInsxX7SUePXOUCUo1xqNorEkIcJjERY2hMPY7x7y4GywA7TNZNZZTM05eoeUaTh+Qc-jaB-GRwQ6YcgME0DhIgvRoM-YYRGoZZ-JsXzQtWcLIP0GDxNwQzIHbNdIH8D5qAWWcWHGXQoI-dsZC49hUiCpKQJSjZROi2L4rGRK5gExqwM2FwelgiTstyuqCqK2gSt-RiQp68LRMG44ziq2yiB81Te3FAcwRkMiPgoPhBmgQIY14Ls1jmPoyNdOhiE23gqwwAB1M5MjI7USUEGMFVoC6bgMbpXsdYZN2IN15X6k5+ueFyyLOuhYCREGwa6SHXAAIQmnwfvoAAZb41klAwJBhoGkZ3WEutoG0gKYAGiDI4GPlB8nKdR1EbhJuVGeZvgKaA6mFgx-wsYYPGvgJ2nAa5sneYJXYczYqXsyGfNJ0LGdizLSsazrBsvDIgkAEEKFiegYxWWFXCTD5hAobkoFzG0TmwPWlfIxFkX0nR0UOej6dJpmwY1GMBnoFZ8xD4EVkSTm4ThuZYThsHhinVY+C+XhcwwEsS31Q2TmQABxNBDcxQ39X1x144RpPyY1JMkxjD56EL7VSA+GNE-x6g0ZEEkmD9N3q-VL5iETNG6A+aFk9T2h0-um1dixZAyzQBUpP9uVh+IIRhmRHd9WJaAYxVD5NqRWf550HHDYATQbC1HptRfK637uE66XZPmWc2Zwv7U04Zx0GjEuJx6wKmQAAaQwIvEsr847vwRhOT2ax9T9QoBgagrhqD-zPnPIBUB0TgOQPnGs1ZC42gVJXICaBfhul4BiTEGBC4YBOIbHGl1yBrEKmQL4mJm6wBNjuXgpxcw4xNPWZAuZMRHBxlWNATs+hECpGkIAA

The problem reproduces after adding the option on `group_1` but not when it's on `group_2`.

More info is in the discussion here:
https://github.com/kieler/elkjs/issues/162

**Comment by soerendomroes** [comment]
The issue is created since `FIXED_ORDER` applies to ports that are not explicitly created.
